### ISSUE TITLE
Think of the following test cases.

### ISSUE THREAD

**Issue by lxconan** [wdwangtw/ArgsParser#2]
https://github.com/wdwangtw/ArgsParser/blob/ea42b7d804ec1b22eeba5c04bcb31df952243276/test/ArgsParserTest/CombinedFlagOptions/when_build_parser_and_parse_args_that_has_combined_flags_then_get_result.cs#L6

* The order of combined flags.
* Suppose there are 3 defined flags options. And 2 of them are provided by a combined flag. Can we correctly get the value of the 3rd flag?

**Comment by wdwangtw** [comment]
It can work. I add some facts to test that.
https://github.com/wdwangtw/ArgsParser/commit/35e5323e06049020988a43aafc97c420cd6fd7cf
``
